In [1]:
import torch

In [2]:
print(torch.__version__)

1.13.1+cu116


Array Discussion

In [20]:
  #Array
array0=torch.tensor((2,3),dtype=torch.float32)
array0

tensor([2., 3.])

In [21]:
#randomaarray
array1=torch.rand((3,3),dtype=torch.float32)
array1

tensor([[0.0229, 0.3896, 0.5513],
        [0.6040, 0.1699, 0.3336],
        [0.1510, 0.7146, 0.9582]])

In [16]:
array2=torch.eye(4,4)
array2

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [19]:
array3=torch.ones((4,4))
array3

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
array4=torch.zeros((4,4))
array4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
arangedata=torch.arange(start=1,end=20,step=2)
arangedata

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [32]:
array5=torch.rand((4,4),dtype=torch.float32)
array5

tensor([[0.9296, 0.6463, 0.0496, 0.3306],
        [0.6484, 0.0840, 0.6407, 0.8283],
        [0.1153, 0.6821, 0.9049, 0.4666],
        [0.2158, 0.7732, 0.1663, 0.1055]])

In [33]:
array6=torch.rand((4,4),dtype=torch.float32)
array6

tensor([[0.8144, 0.5219, 0.9697, 0.8497],
        [0.4447, 0.7785, 0.4854, 0.8163],
        [0.4479, 0.0187, 0.4427, 0.3754],
        [0.8369, 0.4720, 0.6135, 0.8441]])

In [34]:
#tow 4D anrray and multiply them
array7=array5*array6
array7

tensor([[0.7571, 0.3373, 0.0481, 0.2809],
        [0.2883, 0.0654, 0.3110, 0.6762],
        [0.0516, 0.0128, 0.4006, 0.1752],
        [0.1806, 0.3650, 0.1020, 0.0891]])

In [35]:
array4*array7

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])